- hosts: all
  become: yes
  tasks:

  - name: Install necessary system packages for CentOS
    yum:
      name:
        - python3
        - python3-pip
        - git
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Install necessary system packages for Ubuntu
    apt:
      name:
        - python3
        - python3-pip
        - git
        - virtualenv
      state: present
    when: ansible_os_family == 'Debian'


  - name: Ensure ~/.virtualenvs directory exists
    file:
      path: ~/.virtualenvs
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0755'

#  - name: Install virtualenv using pip
#    pip:
#      name: virtualenv
#      executable: pip3
#      extra_args: "--user --trusted-host pypi.tuna.tsinghua.edu.cn"

  - name: Create a virtual environment for the project
    command:
      cmd: "python3 -m virtualenv ~/.virtualenvs/basicframe"
      creates: "~/.virtualenvs/basicframe"


  - name: Synchronize the project directory excluding certain file types
    synchronize:
      src: /home/ptking/src/basicframe/
      dest: ~/projects/basicframe/
      delete: yes  # optional: to delete files in dest that are not in src
      rsync_opts:
        - "--exclude=*.txt"
        - "--exclude=*.log"
        - "--exclude=*.xlsx"
        - "--exclude=*.json"


  - name: Install Python libraries in the virtual environment using requirements.txt
    pip:
      requirements: ~/projects/basicframe/requirements.txt
      state: present
      virtualenv: ~/.virtualenvs/basicframe
      extra_args: '--trusted-host pypi.tuna.tsinghua.edu.cn'
  # Assuming you have other tasks related to setting up or configuring the project, add them here.


