- hosts: all
  become: yes
  tasks:




  - name: Synchronize the project directory excluding certain file types
    synchronize:
      src: /home/ptking/basicframe/
      dest: ~/projects/basicframe/
      delete: yes  # optional: to delete files in dest that are not in src
      rsync_opts:
        - "--exclude=*.txt"
        - "--exclude=*.log"
        - "--exclude=*.xlsx"
        - "--exclude=*.json"




