# Redis配置
redis:
  url: redis://:qunyin@123@124.220.100.192:6379/4      #多文本生产环境库

# MySQL配置
mysql:
  host: 106.15.10.74
  port: 3306
  database: mydatabase
  username: root
  password: root123456

# MongoDB配置
mongodb:
  url: mongodb://root:root123456@139.177.178.116:27017/  #  存储文本的数据库 "mongodb://qychap:qyno11-d@158.247.243.169:18000/?authSource=admin"
  local_url: mongodb://admin:Liupeitao1.@localhost:27017
  siteinfo_url: mongodb://root:root123456@139.177.178.116:27017/ #site info 所在的mongo
  db: mulwenben  # 存储文本的库
  coll: test    # 默认的coll

  db_mul : mulwenben # 存储多语种文本网站的库
  coll_siteinfo: siteinfo


rabbitmq:
  host: localhost
  port: 5672
  username: myuser
  password: mypassword
  virtual_host: myvhost

# Celery配置
celery:
  broker_url: pyamqp://guest:guest@localhost:5672//
  result_backend: redis://:qunyin@123@101.35.228.6:6379/9
  # 其他Celery配置参数...


influxdb:
  token: Sl4Mb6TgyMUis0ic74QWJnVV3G8k6Ic_FSAoRKgtndspoQIsYiKsNKCkPyFrZbIDzMQs6CSM8cvt22ZYmFiMUg==
  org: ptking
  url: http://localhost:8086


logger:
  saved: log