# Redis配置
redis:
  url: redis://:qunyin@123@101.35.228.6:6379/4  # 4 test

# MySQL配置
mysql:
  host: 106.15.10.74
  port: 3306
  database: mydatabase
  username: root
  password: root123456

# MongoDB配置
mongodb:
  db: article  # 默认db
  url: mongodb://root:root123456@106.15.10.74:27017/admin  # "mongodb://qychap:qyno11-d@158.247.243.169:18000/?authSource=admin"
  coll: siteinfo

rabbitmq:
  host: localhost
  port: 5672
  username: myuser
  password: mypassword
  virtual_host: myvhost

# Celery配置
celery:
  broker_url: pyamqp://guest:guest@localhost:5672//
  result_backend: redis://:qunyin@123@101.35.228.6:6379/9
  # 其他Celery配置参数...


influxdb:
  token: Sl4Mb6TgyMUis0ic74QWJnVV3G8k6Ic_FSAoRKgtndspoQIsYiKsNKCkPyFrZbIDzMQs6CSM8cvt22ZYmFiMUg==
  org: ptking
  url: http://localhost:8086


logger:
  saved: log